services:
  db:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis
    networks:
      - app-network
    # Add this to make Redis accessible from host machine if needed
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    command: npm run dev
    networks:
      - app-network

volumes:
  postgres:
    driver: local

networks:
  app-network:
    driver: bridge
