services:
  db:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: always
    networks:
      - app-network
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: openlly
      RABBITMQ_DEFAULT_PASS: openlly
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis
      - rabbitmq
    env_file:
      - .env
    networks:
      - app-network

volumes:
  postgres:
    driver: local

networks:
  app-network:
    driver: bridge
