services:
  db:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest
    restart: always
    networks:
      - app-network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
    resources:
      limits:
        memory: 512M
      reservations:
        memory: 256M

  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: openlly
      RABBITMQ_DEFAULT_PASS: openlly
    ports:
      - "15672:15672"   # Management UI
      - "5672:5672"     # AMQP protocol
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    command: ["/usr/app/wait-for-it.sh", "rabbitmq:5672", "--", "npm", "run", "dev"]
    networks:
      - app-network

volumes:
  postgres:
    driver: local

networks:
  app-network:
    driver: bridge
